# Generated by Django 6.0 on 2025-12-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('lot', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('STRATEGY', 'Strategy')], max_length=10)),
                ('strategy_name', models.CharField(blank=True, choices=[('EMA_CROSS', 'EMA Crossover'), ('EMA_TREND', 'EMA Trend')], max_length=50, null=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
