# Generated by Django 6.0 on 2025-12-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_mt5account_tradehistory_tradingbot_delete_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5account',
            old_name='login',
            new_name='account_id',
        ),
    ]
