# Generated by Django 6.0 on 2025-12-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_login_mt5account_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5account',
            old_name='account_id',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='tradingbot',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mt5account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tradingbot',
            name='status',
        ),
        migrations.AddField(
            model_name='mt5account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingbot',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.mt5account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingbot',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mt5account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradingbot',
            name='strategy',
            field=models.CharField(choices=[('ema_cross', 'EMA Crossover'), ('ema_trend', 'EMA Trend'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=10)),
                ('lot', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tradingbot')),
            ],
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
    ]
