# Generated by Django 6.0 on 2025-12-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_account_id_mt5account_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='tradingbot',
            name='user',
        ),
    ]
