# Generated by Django 6.0 on 2025-12-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_mt5account_balance_remove_tradingbot_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='Tradehistory',
        ),
        migrations.RemoveField(
            model_name='mt5account',
            name='user',
        ),
    ]
