# Generated by Django 6.0 on 2026-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_trade_tradehistory_remove_mt5account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='sl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
