# Generated by Django 6.0 on 2026-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_tradehistory_sl_tradehistory_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingbot',
            name='session',
            field=models.CharField(choices=[('asia', 'Asia Session'), ('london', 'London Session'), ('newyork', 'New York Session'), ('london_ny', 'London - New York Overlap'), ('all', 'All Sessions')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingbot',
            name='strategy',
            field=models.CharField(choices=[('ema_cross', 'EMA Crossover'), ('ema_trend', 'EMA Trend'), ('manual', 'Manual'), ('ema_rsi', 'EMA - RSI Confirmation'), ('adx_ema_mtf', 'EMA MTF - ADX')], max_length=20),
        ),
    ]
